apiVersion: v1
kind: Secret
metadata:
  name: study-planner-secret
  namespace: study-planner
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"